const SESSION_STATES = {
  NEW: 'NEW',
  AWAITING_BIRTH_DATE: 'AWAITING_BIRTH_DATE',
  AWAITING_HOOK_RESPONSE: 'AWAITING_HOOK_RESPONSE',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  ACTIVE: 'ACTIVE',
  SESSION_ENDED: 'SESSION_ENDED',
  MINOR_REJECTED: 'MINOR_REJECTED',
};

const SESSION_DURATION_MS = 60 * 60 * 1000;
const MIN_PAYMENT_PEN = 4.9;
const YAPE_PHONE = '952989503';
const YAPE_PHONE_DISPLAY = '952 989 503';
const MIN_AGE = 18;
const SESSION_WARNING_MINUTES = 10;

module.exports = {
  SESSION_STATES,
  SESSION_DURATION_MS,
  MIN_PAYMENT_PEN,
  YAPE_PHONE,
  YAPE_PHONE_DISPLAY,
  MIN_AGE,
  SESSION_WARNING_MINUTES,
};
