const SESSION_STATES = {
  NEW: 'NEW',
  AWAITING_BIRTH_DATE: 'AWAITING_BIRTH_DATE',
  AWAITING_FREE_SIGNAL_2: 'AWAITING_FREE_SIGNAL_2',
  AWAITING_FREE_SIGNAL_3: 'AWAITING_FREE_SIGNAL_3',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  ACTIVE: 'ACTIVE',
  SESSION_ENDED: 'SESSION_ENDED',
  MINOR_REJECTED: 'MINOR_REJECTED',
  /** @deprecated legacy funnel state — treated like AWAITING_FREE_SIGNAL_3 */
  AWAITING_HOOK_RESPONSE: 'AWAITING_HOOK_RESPONSE',
};

const SESSION_DURATION_MS = 30 * 60 * 1000;
const MIN_PAYMENT_PEN = 4.9;
const YAPE_PHONE = '952989503';
const YAPE_PHONE_DISPLAY = '952 989 503';
const MIN_AGE = 18;
const SESSION_WARNING_MINUTES = 5;

const FUNNEL_VERSION = 2;
const STALE_MID_FUNNEL_MS = 72 * 60 * 60 * 1000;
const STALE_BIRTH_DATE_MS = 7 * 24 * 60 * 60 * 1000;
const SESSION_EXPIRY_POLL_MS = 60 * 1000;

module.exports = {
  SESSION_STATES,
  SESSION_DURATION_MS,
  MIN_PAYMENT_PEN,
  YAPE_PHONE,
  YAPE_PHONE_DISPLAY,
  MIN_AGE,
  SESSION_WARNING_MINUTES,
  FUNNEL_VERSION,
  STALE_MID_FUNNEL_MS,
  STALE_BIRTH_DATE_MS,
  SESSION_EXPIRY_POLL_MS,
};
